version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
artifacts:
  files:
    - .\bin\Debug\netcoreapp1.0\*
  name: web.zip
  secondary-artifacts:
    hangfire:
      files: '**/*'
      name: hangfire.zip
